// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvefnevyqzmmognumvzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2ZWZuZXZ5cXptbW9nbnVtdnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzMyMjksImV4cCI6MjA1NTA0OTIyOX0.1xF-9v5cAtpC2-Q815Ppu05TdY5bnI-xEHbZP_b-FFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);